library("readxl")
library("xlsx")
library("dplyr")
library("stringr")
library("lubridate")
library("reshape2")
library("tidyr")  
library("zoo")
library("rvest")
library("RCurl")
library("stringi")
library("BatchGetSymbols")
library("plotly")
library("sidrar")
library("ipeadatar")

source("crawler_CVM.R")
source("DRE.R")
source("BP.R")
source("B3.R")
source("ticker_empresa.R")
source("construir_release.R")
source("construir_bd.R")
source("atualizar_ponta.R")
source("num_acoes.R")
source("metricas_empresas_pordata.R")
source("metricas_porempresa.R")
source("acoes.R")
source("construir_cotacao.R")
source("fundamentus.R")
source("sidra.R")
source("SGS.R")





